### ISSUE TITLE
GUI interaction reference page doesn't exist.

### ISSUE THREAD

**Issue by Tcll** [MinecraftForge/Documentation#97] opened 2017-04-09 13:32 UTC
was looking for docs on dimension ID to/from NBT when I stumbled across the GUI portion.
it says more​information at link, but the page is invalid.

shouldn't this have been documented directly to prevent issue like this?

**Comment by elifoster** [comment] 2017-04-09 15:17
Duplicate of #74

**Comment by Tcll** [comment] 2017-04-09 15:32
oops, sorry, I see it now, feel free to close this one

**Closed** 2017-04-10 17:46 UTC
