### ISSUE TITLE
[BUG]Error link when not at home

### ISSUE THREAD

**Issue by Ecdcaeb** [MinecraftForge/Documentation#524] opened 2024-01-22 04:46 UTC
![image](https://github.com/MinecraftForge/Documentation/assets/107909747/85665f20-0503-4334-8d64-04e41785857d)

Step 1:
Open any item
Step 2:
Click another item.
Its link will be added directly after the existing link.

This was fixed at 1.14. x, but past documents are still affected.

**Comment by Jonathing** [comment] 2024-01-22 17:15
Easily reproducible. Thanks.

**Comment by ChampionAsh5357** [comment] 2024-01-23 00:28
It seems this issue can be fixed by copying the `forge_theme` from later versions back to 1.12.x and 1.13.x. I'll take a proper stab at it tomorrow.

**Comment by ChampionAsh5357** [comment] 2024-01-23 21:35
Issue seems to be resolved now, closing.

**Closed as completed by ChampionAsh5357** 2024-01-23 21:35 UTC
Labels: Theme
